version: "3"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
volumes:
  gohome: